export const Actions = {
    GET_ALL_PRODUCTS:'GET_ALL_PRODUCTS',
    GET_SINGLE_PRODUCT : 'GET_SINGLE_PRODUCT',
    UPDATE_PRODUCT: 'UPDATE_PRODUCT',
    CREATE_PRODUCT: 'CREATE_PRODUCT',
    DELETE_PRODUCT:'DELETE_PRODUCT',
    UPDATE_RECENT_PRODUCTS: 'UPDATE_RECENT_PRODUCTS' ,   
    SORT_BY_HIGH_PRICE: 'SORT_BY_HIGH_PRICE',    
    SORT_BY_LOW_PRICE: 'SORT_BY_LOW_PRICE',
    RESET_PRODUCT_SORTING: 'RESET_PRODUCT_SORTING', 
    FILTER_PRODUCT_SORTING: 'FILTER_PRODUCT_SORTING' 
} as const

export type ActionsType = typeof Actions[keyof typeof Actions]